import { Dashboard } from "@material-ui/icons";
import Head from "next/head";

import React from "react";

export default function index() {
  return (
    <div>
      <Head>
        <title>Swanslate</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Dashboard />
    </div>
  );
}
